name: Update umbrel-app.yml metadata version

on: push

jobs:
  update-umbrel-app:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - uses: CPardi/update-umbrel-app-action@b8d3a8f54169fa942ad695e8b935d64c94aa7eb9
        with:
          source_service_name: web
