name: Update umbrel-app.yml metadata version

on: push

jobs:
  update-umbrel-app:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - uses: CPardi/update-umbrel-app-action@08c0417f7e0b09165084a9d7278346c83ce4e198
        with:
          source_service_name: web
