name: Update Umbrel version

on: push

jobs:
  update-umbrel-app:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - uses: CPardi/umbrel-update-action@53318d25bf3f001d38b8242e2e7bbe9b5e26ac85
        with:
          source_service_name: web
