name: Update umbrel-app.yml metadata version

on: push

jobs:
  update-umbrel-app:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - uses: CPardi/update-umbrel-app-action@5ea9011bafb76dd37a8dbb7cb64da8d0df393dae
        with:
          source_service_name: web
